version: '3'
services:
  data-api:
    build:
      context: .
      # args:
        # NODE_VERSION: 6.10.2
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongodb:footifydb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
